server:
  port: 8080

spring:
  application:
    name: ms.service

  profiles:
    active: ${ACTIVE_PROFILE:local}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

redis:
  server:
    urls: redis://localhost:6379